#!/bin/sh

SERVICE="laptop-mode"

[ -e "/bin/svc.d/default/$SERVICE" ] && . "/bin/svc.d/default/$SERVICE"

BIN="/usr/sbin/$SERVICE"

case $1 in
	-s)
		[ ! -d /run/laptop-mode-tools ] && install -d /run/laptop-mode-tools
		rm -f /run/laptop-mode-tools/*
		touch /run/laptop-mode-tools/enabled
		$BIN auto 2>&1 >/dev/null
		;;
	-k)
		rm -f /run/laptop-mode-tools/enabled
		$BIN stop 2>&1 >/dev/null
		;;
	*)
		echo "usage: $0 -s|-k"
		exit 1
esac

