#! /bin/sh
# This script returns the base arch for a tuple.
# This is used for include paths, etc. where endian-ness,
# for example, doesn't matter.
#
case "$1" in
# Catch these early to simplify matching for 32-bit archs
arm64*|aarch64*) ARCH=aarch64 ;;
arm*) ARCH=arm ;;
thumb*) ARCH=arm ;;
cortex*) ARCH=arm ;;
x86_32*|i?86*) ARCH=i386 ;;
x86_64-x32*|x32*|x86_64*x32) ARCH=x32 ;;
x86_64*) ARCH=x86_64 ;;
mips64*) ARCH=mips64 ;;
mips*) ARCH=mips ;;
microblaze*) ARCH=microblaze ;;
ppc64*) ARCH=ppc64 ;;
ppc*) ARCH=ppc ;;
sh[1-9bel-]*|sh|superh*) ARCH=sh ;;
*) echo unknown && exit 1 ;;
esac
echo $ARCH
