#! /bin/sh
# This script returns the arch for a tuple.
#
case "$1" in
arm64*|aarch64*) ARCH=aarch64 ;;
arm*eb*) ARCH=armeb ;;
arm*) ARCH=arm ;;
thumb*) ARCH=arm ;;
cortex*) ARCH=arm ;;
x86_32*|i?86*) ARCH=i386 ;;
x86_64-x32*|x32*|x86_64*x32) ARCH=x32 ;;
x86_64*) ARCH=x86_64 ;;
mips64*) ARCH=mips64 ;;
mipsel*) ARCH=mipsel ;;
mips*) ARCH=mips ;;
microblaze*) ARCH=microblaze ;;
ppc64el*) ARCH=ppc64el ;;
ppc64*) ARCH=ppc64 ;;
ppc*|powerpc*) ARCH=ppc ;;
sh[1-9bel-]*|sh|superh*) ARCH=sh ;;
*) echo unknown && exit 1 ;;
esac
echo $ARCH
