#! /bin/sh
# This script returns the arch for a tuple.
#
case "$1" in
armv6*) ARCH=armv6 ;;
arm*sf) ARCH=armsf ;;
arm*) ARCH=armhf ;;
mips*sf) ARCH=mipssf ;;
mips*) ARCH=mipshf ;;
*) echo unknown && exit 1 ;;
esac
echo $ARCH
