#! /usr/bin/env python
import subprocess
p = subprocess.Popen(["find", "-type", "f", "-name", "*.html"], stdout=subprocess.PIPE)
out, err = p.communicate()

GA = """
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-38388212-1', 'auto');
  ga('send', 'pageview');

</script>
"""

for file in out.split('\n'):
    file = file.strip()
    if file != '':
        f = open(file, 'r')
        contents = f.read()
        f.close()
        where = contents.find('UA-38388212-1')
        if where == -1:
            where = contents.find('</head>')
            if where != -1:
                f = open(file, 'w')
                newcontents = contents[0:where] + GA + contents[where:]
                f.write(newcontents)
                f.close()
