#!/bin/sh
# toplevel ELLCC distribution build script

# Get the staging directory.
prefix=`pwd`

# Figure out the compilers to use.
. ./build-setup $*

echo Building ecc with:
echo C compiler: $CC
echo C++ compiler: $CXX
echo In: llvm-build$builddir

# Configure for an LLVM+Clang build.
mkdir -p llvm-build$builddir
cd llvm-build$builddir
../llvm/configure --bindir=$bindir --prefix=$prefix --enable-optimized --enable-shared=no \
                  || exit 1
# Build and install the LLVM tools.
make -j 6 || exit 1
cd ..

# Configure and build the GNU tools.
cd gnu
./build || exit 1
cd ..

# Now install the ELLCC tools.
make -j 6 -C llvm-build$builddir install || exit 1

if [ "$host" != "$build" ] ; then
  # The host system is not the build system.
  # No nead to build the libraries again.
  exit 0
fi

# Build libecc.
cd libecc
make clean
make || exit 1
cd ..

if [ $haslibs -eq 0 ] ; then
  echo "Please run the build script again to bootstrap ecc."
  echo "This may be done a few times:"
  echo "1. ecc is built with gcc and host libraries."
  echo "2. ecc is built with itself (compiled with gcc) and libecc."
  echo "3. ecc is built with itself (compiled with itself) and libecc."
fi
