#!/bin/sh
# toplevel ELLCC distribution build script

# OG: Debug feature to find out where the errors come from...
bailout () {
  echo $1
  echo "Error: leaving module $cwd"
  exit 1
}


# Get the staging directory.
prefix=`pwd`

# Figure out the compilers to use.
. ./build-setup $*

# Configure for an LLVM+Clang build.
mkdir -p llvm-build$builddir

${MAKE} DIR=llvm-build$builddir CC="$cc" CXX="$cxx" AR="$ar" RANLIB="$ranlib" \
     TARGET=$host OS=$os TUPLE=$tuple \
     bindir=$bindir prefix=$prefix build=$build haslibs=$haslibs \
     llvm.configure || bailout "Configure failed for llvm"

# Build the LLVM tools.
${MAKE} -C llvm-build$builddir -j ${maxjobs} || bailout "Make failed for llvm"

# Build the GNU tools.
cd gnu
./build $arg1 || bailout "Build failed for gnu"
cd ..

# Now install the ELLCC tools.
${MAKE} -j ${maxjobs} -C llvm-build$builddir install || bailout "Install failed for llvm"

if [ "$host" != "$build" ] ; then
  # The host system is not the build system.
  # No need to build the libraries again.

  echo Configured to $WHY.
  echo C compiler: $cc
  echo C++ compiler: $cxx
  echo In: llvm-build$builddir
  exit 0
fi

# Build libecc.
cd libecc
${MAKE} clean
${MAKE} || bailout "Make failed for libecc"
cd ..

if [ "x$hostos" = "xLinux" ] ; then
  if [ "$haslibs" != "yes" ] ; then
    echo "Please run the build script again to bootstrap ecc."
    echo "This may be done a few times:"
    echo "1. ecc is built with itself (compiled with gcc) and libecc."
    echo "2. ecc is built with itself (compiled with itself) and libecc."
  fi
fi
