#!/bin/sh
# toplevel ELLCC distribution build script

# OG: Debug feature to find out where the errors come from...
bailout () {
  echo $1
  echo "Error: leaving module $cwd"
  exit 1
}


# Get the staging directory.
prefix=`pwd`

all=0
package=""
while [ $# -gt 0 ] ; do
  case $1 in
    -a)
      # Build all configurations except host.
      all=1
      shift
      ;;
    -p)
      # package all configurations.
      shift
      package=$1
      shift
      ;;
    *)
      break
      ;;
  esac
done

# Figure out the compilers to use.
. ./build-setup $*
if [ $debug -ne 0 ] ; then
  echo $WHY
  echo host=$host
  echo build=$build
  echo os=$os
  echo hostos=$hostos
  echo tuple=$tuple
  echo libtuple=$libtuple
  echo cc=$cc
  echo cxx=$cxx
  echo hcc=$hcc
  echo hcxx=$hcxx
  echo ar=$ar
  echo ranlib=$ranlib
  echo builddir=$builddir
  echo bindir=$bindir
  echo haslibs=$haslibs
  echo maxjobs=$maxjobs
  exit 0
fi

if [ $all -eq 1 ] ; then
  # Build all configurations except host.
  BldConfigs=`cat buildhosts | grep -v ^#`
  for config in $BldConfigs ; do
    # Don't rebuild the host.
    if [ `bin/ecc-getarch $config`-`bin/ecc-getos $config` = $host-$hostos ] ; then
      continue
    fi
    # The microblaze can't self host.
    if [ `bin/ecc-getarch $config` = microblaze ] ; then
      continue
    fi
    ./build $config || bailout "Build failed for $config"
  done
    # RICH: ./build -m || bailout "Build failed for MinGW"
  exit 0
fi

if [ "$package" != "" ] ; then
  # Package all configurations.
  BldConfigs=`cat buildhosts | grep -v ^#`
  for config in $BldConfigs ; do
    # The microblaze can't self host.
    if [ `bin/ecc-getarch $config` = microblaze ] ; then
      continue
    fi
    if [ ! -e llvm-build-$config ] ; then
      echo "$config packaging failed because it hasn't been built"
      bailout "Packaging failed for $config"
    else
      ./mkdist $config $package || bailout "Packaging failed for $config"
    fi
  done
  exit 0
fi

# Copy extra bin scripts.
mkdir -p $bindir
cp -p bin-extra/* $bindir

# Configure for an LLVM+Clang build.
mkdir -p llvm-build$builddir

if [ -e bin/llvm-tblgen -a \( "`basename $bindir`" != "bin" \) ] ; then
  # We have tblgens built.
  CROSS_CMAKE_FLAGS="-DCMAKE_CROSSCOMPILING=True \
      -DLLVM_TABLEGEN=`pwd`/bin/llvm-tblgen \
      -DCLANG_TABLEGEN=`pwd`/bin/clang-tblgen"
else
  CROSS_CMAKE_FLAGS=
fi
if [ "$os" = "mingw32" ] ; then
  CROSS_CMAKE_FLAGS="$CROSS_CMAKE_FLAGS -DWIN32=True"
fi
${MAKE} DIR=llvm-build$builddir CC="$cc" CXX="$cxx" AR="$ar" RANLIB="$ranlib" \
     TARGET=$host OS=$os HOSTOS=$hostos TUPLE=$tuple \
     install=$install build=$build haslibs=$haslibs \
     cross_cmake_flags="$CROSS_CMAKE_FLAGS" \
     llvm.configure || bailout "Configure failed for llvm"

# Build the LLVM tools.
${MAKE} -C llvm-build$builddir -j ${maxjobs} || bailout "Make failed for LLVM"

# Build the GNU tools.
cd gnu
  ./build $arg1 || bailout "Build failed for gnu"
cd ..

# Install LLVM components.
${MAKE} -j ${maxjobs} -C llvm-build$builddir install ||  bailout "Install failed for LLVM"

# Now install the LLVM tools in the appropriate bin directory.
rm -f $bindir/clang-[0-9]*
cp llvm-build$builddir/bin/* $bindir
cd $bindir
ln -sf clang-[0-9]* ecc
ln -sf clang-[0-9]* ecc++
cd - 

if [ "$host" != "$build" ] ; then
  # The host system is not the build system.
  # No need to build the libraries again.

  echo Configured to $WHY.
  echo C compiler: $cc
  echo C++ compiler: $cxx
  echo In: llvm-build$builddir
  exit 0
fi

# Build libecc.
cd libecc
${MAKE} || bailout "Make failed for libecc"
cd ..

if [ "x$hostos" = "xlinux" ] ; then
  if [ "$haslibs" != "yes" ] ; then
    # Make sure ELLCC_ARG0 is set in the next build.
    find llvm-build* -name driver.o | xargs rm -f
    echo "Please run the build script again to bootstrap ecc."
    echo "This may be done a few times:"
    echo "1. ecc is built with itself (compiled with gcc) and libecc."
    echo "2. ecc is built with itself (compiled with itself) and libecc."
  fi
fi
