#! /bin/sh
if [ $# -ne 1 ] ; then
    echo "$0: <version>"
    exit 1
fi
OSX=Mac_OS_X_`sw_vers -productVersion`
name=ellcc-$OSX-$1.tgz

make -C examples distclean
files=`sed -e "s:\(.*\):ellcc/\1:" ellcc.files`
cd ..; tar cvfpz ellcc/$name $files ; cd -
echo created $name
