#! /bin/sh
OSX=Mac_OS_X_`sw_vers -productVersion`
name=ellcc-$OSX-`date +%Y-%b-%d-%H-%M-%S`.tgz

make -C baremetal clean
cd ..; tar cvfpz ellcc/$name -T ellcc/ellcc.files -T ellcc/ellcc.bin.files; cd -
echo created $name
