#! /bin/sh
if [ $# -ne 2 ] ; then
    echo "$0: <name> <revision>"
    exit 1
fi

NAME=$1
shift
cd libecc/src
svn merge --accept edit http://ellcc.org/svn/vendor/${NAME}/$1 http://ellcc.org/svn/vendor/${NAME}/current ${NAME}
