#! /bin/sh
MINGW=MinGW
if [ $# -ne 2 ] ; then
    echo "$0: <configuration> <version>"
    exit 1
fi
name=ellcc-$1-$2.tgz

make -C baremetal clean

if [ ! -e bin-$MINGW ] ; then
  echo "The MinGW bin directory doesn't exist."
  exit 1;
fi

mv bin bin.save
ln -s bin-$MINGW bin

rm -fr bin/ecc++.exe
cp bin/ecc.exe bin/ecc++.exe
rm -fr bin/llvm-ranlib.exe
cp bin/llvm-ranlib.exe bin/llvm-ranlib.exe
pwd=`pwd`
pwd=`basename $pwd`
files=`sed -e "s:\(.*\):$pwd/\1:" ellcc.files`
cd ..; tar cvfpz $pwd/$name $files; cd -
rm bin
mv bin.save bin
echo created $name
