#! /bin/sh
MINGW=MinGW
if [ $# -ne 1 ] ; then
    echo "$0: <configuration-version>"
    exit 1
fi
name=ellcc-$1.tgz

make -C baremetal clean

if [ ! -e bin-$MINGW ] ; then
  echo "The MinGW bin directory doesn't exist."
  exit 1;
fi

mv bin bin.save
ln -s bin-$MINGW bin

rm -fr bin/ecc++.exe
cp bin/ecc.exe bin/ecc++.exe
rm -fr bin/llvm-ranlib.exe
cp bin/llvm-ranlib.exe bin/llvm-ranlib.exe
cd ..; tar cvfpz ellcc/$name -T ellcc/ellcc.files; cd -
rm bin
mv bin.save bin
echo created $name
