#! /bin/sh
if [ $# -ne 2 ] ; then
    echo "$0: <configuration> <version>"
    exit 1
fi
name=ellcc-$1-$2.tgz

nonnative=0
if [ -e bin-$1 ] ; then
  # The non-native bin directory exists.
  mv bin bin.save
  mv bin-$1 bin
  nonnative=1
fi
pwd=`pwd`
pwd=`basename $pwd`
deref=
regex='.*-w64-mingw'
if [[ $1 =~ $regex ]] ; then
  deref=-h
fi
make -C examples distclean
files=`sed -e "s:\(.*\):$pwd/\1:" ellcc.files`
cd ..; tar $deref --transform="s:$pwd/:ellcc/:" -cvpz -f $pwd/$name $files ; cd -
if [ $nonnative -ne 0 ] ; then
  mv bin bin-$1
  mv bin.save bin
fi
echo created $name
