/* Choose elk features to pull in. */

EXTERN(__elk_fdconsole)
EXTERN(__elk_simple_memman)
EXTERN(__elk_command)
EXTERN(__elk_thread)
EXTERN(__elk_time)
EXTERN(__elk_time_commands)
EXTERN(__elk_test_commands)
EXTERN(__elk_vfs_syscalls)
EXTERN(__elk_devfs)
EXTERN(__elk_ramfs)
EXTERN(__elk_fifofs)
EXTERN(__elk_mkdir_bin)
EXTERN(__elk_ls_bin)
EXTERN(__elk_cat_bin)
EXTERN(__elk_pwd_bin)
EXTERN(__elk_echo_bin)

