#!/bin/sh
# MIT/X Consortium License
#
# © 2012-14 Christoph Lohmann <20h@r-36.net>
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

if [ $# -lt 2 ];
then
	printf "usage: %s [start|stop|restart] service\n" "$(basename "$0")" \
		>&2
	exit 1
fi

cmd="$1"
service="$2"

case "$cmd" in
sta*)
	svc -s "$service"
	;;
sto*)
	svc -k "$service"
	;;
r*)
	svc -r "$service"
	;;
*)
	printf "usage: %s [start|stop|restart] service\n" "$(basename "$0")" \
		>&2
	exit 1
	;;
esac

